### ISSUE TITLE
TypeError: LephareInformer.__init__() got an unexpected keyword argument 'aliases'

### ISSUE THREAD

**Issue by hdante** [LSSTDESC/rail_lephare#54]
Hello, when calling `LephareInformer.make_stage()`, an error is returned:

```
(base) [henrique.almeida@loginapl01 testlephare]$ rail-train -a lephare ~/data/ref/training_set_dp0.2.pq 
Start: 2024-08-15 10:29:18.498113
Estimator algorithm: lephare
Bins: 301
HDF5 group name: ""
Column template for magnitude data: "mag_{band}"
Column template for error data: "magerr_{band}"
Extra parameter file: "None"
Starting setup.
Loading all program modules...
User defined LEPHAREDIR is set. Code runs depend on all required
auxiliary data being present at /lustre/t1/cl/lsst/tmp/henrique.almeida/lephare-data.
LEPHAREWORK is being set to the default cache directory:
/lustre/t1/cl/lsst/tmp/henrique.almeida/slurm-home/var/cache/lephare/work
Default work cache is already linked. 
This is linked to the run directory:
/lustre/t1/cl/lsst/tmp/henrique.almeida/slurm-home/var/cache/lephare/runs/20240814T192302
Number of keywords read in the config file: 86
Number of keywords read in the config file: 86
Configuring trainer...
Traceback (most recent call last):
  File "/lustre/t1/cl/lsst/tmp/henrique.almeida/slurm-home/bin/rail-train", line 212, in <module>
    if __name__ == '__main__': main()
                               ^^^^^^
  File "/lustre/t1/cl/lsst/tmp/henrique.almeida/slurm-home/bin/rail-train", line 202, in main
    ctx = setup(cfg)
          ^^^^^^^^^^
  File "/lustre/t1/cl/lsst/tmp/henrique.almeida/slurm-home/bin/rail-train", line 166, in setup
    trainer = setup_trainer(cfg.estimator, cfg.output, cfg.column_template,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/t1/cl/lsst/tmp/henrique.almeida/slurm-home/bin/rail-train", line 139, in setup_trainer
    trainer = Trainer.make_stage(**all_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/ceci/stage.py", line 123, in make_stage
    stage = cls(kwcopy, comm=comm, aliases=aliases)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LephareInformer.__init__() got an unexpected keyword argument 'aliases'
```

Versions:
- rail_lephare 0.2 (from PyPI)
- lephare 0.1.11.dev4+gff46ff8 (from main branch)
- python 3.11.9 (from conda default channel)
- ceci 2.0.1 (from PyPI)

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [x] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by mairanteodoro** [comment]
Any updates on this bug?
